### ISSUE TITLE
Crtl + C will throw exception when quit application

### ISSUE THREAD

**Issue by danielk1031** [danielk1031/netconsole#3]
``` bash
Listen to port 6666

Leave Netconsole Client.

Traceback (most recent call last):
  File "./netconsole.py.latest", line 104, in <module>
    client1.worker_send()
  File "./netconsole.py.latest", line 61, in worker_send
    th_send.join()
  File "/usr/lib/python2.7/threading.py", line 949, in join
    self.__block.wait()
  File "/usr/lib/python2.7/threading.py", line 339, in wait
    waiter.acquire()
KeyboardInterrupt
```

**Comment by danielk1031** [comment]
Fixed at commit 13cc65f11f10e7417b3109aca86078d2dab3c14d
